Fixing PETSC installation on Archlinux

diff --git a/install b/install
--- a/install
+++ b/install
@@ -214,6 +214,20 @@ if [ ! -d "$i_dir/PETSC" -o ! -d "$i_dir/EIGEN" ]; then
     else
       inst_lin_alg="y"
     fi
+
+    ### PETSC require Python
+
+    command -v python
+    if [ $? -ne 0 ]; then
+      ### We have to install python
+      echo "OpenFPM require python but it's not installed, searching a solution... "
+      solve_python
+      command -v python
+      if [ $? -ne 0 ]; then
+	echo -e "python\033[91;5;1m FAILED \033[0m"
+        return
+      fi
+    fi
 fi
 
 lin_alg_dir=""
