Fixing jenkins scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -49,6 +49,39 @@ if [ $? -ne 0 ]; then
   echo -e "Configure\033[91;5;1m FAILED \033[0m"
   exit 1
 fi
+# pull from all the projects
+cd openfpm_data
+git pull origin develop
+if [ $? -ne 0 ]; then
+  echo -e "Configure\033[91;5;1m FAILED \033[0m"
+  exit 1
+fi
+cd ..
+
+cd openfpm_devices
+git pull origin master
+if [ $? -ne 0 ]; then
+  echo -e "Configure\033[91;5;1m FAILED \033[0m"
+  exit 1
+fi
+cd ..
+
+cd openfpm_vcluster
+git pull origin master
+if [ $? -ne 0 ]; then
+  echo -e "Configure\033[91;5;1m FAILED \033[0m"
+  exit 1
+fi
+cd ..
+
+cd openfpm_io
+git pull origin master
+if [ $? -ne 0 ]; then
+  echo -e "Configure\033[91;5;1m FAILED \033[0m"
+  exit 1
+fi
+cd ..
+
 git submodule update
 if [ $? -ne 0 ]; then
   echo -e "Configure\033[91;5;1m FAILED \033[0m"
