Fixing installation of SUITESPARSE to ignore default installation of blas or lapack

diff --git a/install b/install
--- a/install
+++ b/install
@@ -183,6 +183,18 @@ else
             LAPACK_installed=1
             blas_options="--with-blas=-L/home/i-bird/OPENBLAS/lib/ -lopenblas"
         elif [ $conf_err -eq 205 ]; then
+            ## First we install openblas, we ignore default lapack
+            ## this SuiteSparse is programmed to use libopenblas
+            echo "Lapack not found try to install"
+            if [ $LAPACK_installed -eq 1  ]; then
+                echo "Error the installation of LAPACK failed"
+                exit 1
+            fi
+            ./script/install_OPENBLAS.sh $i_dir $compiler_opt
+            LAPACK_installed=1
+            blas_options="--with-blas=-L/home/i-bird/OPENBLAS/lib/ -lopenblas"
+        
+            ## Then suite sparse
             echo "SuiteSparse not found try to install"
             if [ $SUITESPARSE_installed -eq 1  ]; then
                 echo "Error the installation of SuiteSparse failed"
