Fixing PATH folder

diff --git a/script/detect_gcc b/script/detect_gcc
--- a/script/detect_gcc
+++ b/script/detect_gcc
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+function haveProg() {
+    [ -x "$(command -v $1)" ]
+}
+
 function gpp_clang()
 {
     if [ x"$dgc_compiler" == x"g++" ]; then
@@ -15,12 +19,10 @@ function gpp_clang()
     fi
 }
 
-
 function detect_compiler()
 {
     gpp_found=0
     icpc_found=0
-
     dgc_ret=0
 
      if [ x"$CXX" != x"" -o x"$CC" != x"" -o x"$F77" != x"" -o x"$FC" != x"" ]; then
@@ -64,11 +66,10 @@ function detect_compiler()
     fi
 
     # First we try to understand if g++ command line is linked to clang
-    
-    g++ --version | grep "Apple LLVM"
-    if [ $? == 0 ]; then
-        echo "Apple LLVM based g++"
+    if haveProg g++; then
 
+      g++ --version | grep "Apple LLVM" >/dev/null 2>&1
+      if [ $? == 0 ]; then
         echo "Apple LLVM based g++"
 
         # we try the detect the version
@@ -105,13 +106,13 @@ function detect_compiler()
              dgc_ret=1
              gpp_found=1
            fi
-		else
-        	dgc_ret=2
+        else
+           dgc_ret=2
         fi
-    fi
+      fi
 
-    g++ --version | grep g++
-    if [ $? == 0 -a gpp_found -ne 1 ]; then
+      g++ --version | grep "g++" > /dev/null 2>&1
+      if [ $? == 0 -a $gpp_found -ne 1 ]; then
         dgc_major=$(g++ --version | grep g++ | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/g')
         dgc_middle=$(g++ --version | grep g++ | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/g')
         dgc_minor=$(g++ --version | grep g++ | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/g')
@@ -144,10 +145,44 @@ function detect_compiler()
           dgc_ret=0
           gpp_found=0
         fi
+      fi
+
+      g++ --version | grep "clang" > /dev/null 2>&1
+      if [ $? == 0 $gpp_found -ne 1 ]; then
+        dgc_major=$(g++ --version | grep g++ | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/g')
+        dgc_middle=$(g++ --version | grep g++ | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/g')
+        dgc_minor=$(g++ --version | grep g++ | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/g')
+
+        if [ $dgc_major -gt 3 ]; then
+          echo -e "g++ $dgc_major.$dgc_middle.$dgc_minor \033[92;1m SUCCESS \033[0m"
+          dgc_compiler=clang++
+          dgc_ret=1
+          gpp_found=1
+        elif [ $dgc_major -lt 3 ]; then
+          echo -e "g++ $dgc_major.$dgc_middle.$dgc_minor  \033[91;5;1m FAILED \033[0m your clang version is too old 3.6.0 at least required"
+          dgc_ret=0
+          gpp_found=0
+        elif [ $dgc_middle -gt 6  ]; then
+          echo -e "g++ $dgc_major.$dgc_middle.$dgc_minor \033[92;1m SUCCESS \033[0m"
+          dgc_compiler=clang++
+          dgc_ret=1
+          gpp_found=1
+        elif [ $dgc_middle -lt 6 ]; then
+          echo -e "g++ $dgc_major.$dgc_middle.$dgc_minor \033[91;5;1m FAILED \033[0m your clang version is too old 3.6.0 at least required"
+          dgc_ret=0
+          gpp_found=0
+        else
+          echo -e "g++ $dgc_major.$dgc_middle.$dgc_minor \033[92;1m SUCCESS \033[0m"
+          dgc_compiler=clang++
+          dgc_ret=0
+          gpp_found=0
+        fi
+      fi
     fi
 
-    icpc --version | grep icpc
-    if [ $? == 0 -a x"icpc" == x"icpc" ]; then
+    if haveProg icpc; then
+      icpc --version | grep icpc > /dev/null 2>&1
+      if [ $? == 0 ]; then
         dgc_major=$(icpc --version | grep icpc | sed 's/.*\([0-9][0-9]\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/g')
         dgc_middle=$(icpc --version | grep icpc | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/g')
         dgc_minor=$(icpc --version | grep icpc | sed 's/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/g')
@@ -172,6 +207,7 @@ function detect_compiler()
           dgc_ret=1
           icpc_found=1
         fi
+      fi
     fi
 
     ### If we detect more than one valid compiler ask to choose
