Fixing nodejs installation

diff --git a/script/install_gdbgui b/script/install_gdbgui
--- a/script/install_gdbgui
+++ b/script/install_gdbgui
@@ -8,6 +8,51 @@ source script/solve_npm_yarn
 source script/show_solutions
 source script/solve_gdbserver
 source script/discover_package_manager
+source script/solve_nodejs
+
+node_js_inst
+
+if haveProg node; then
+
+  dgc_major=$(node --version | grep v | sed 's/v\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)/\1/g')
+  dgc_middle=$(node --version | grep v | sed 's/v\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)/\2/g')
+  dgc_minor=$(node --version | grep v | sed 's/v\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)/\3/g')
+
+  if [ x"$dgc_major" = x"10" -a x"$dgc_middle" -gt x"14"  ]; then 
+    echo -e "node\033[92;1m SUCCESS \033[0m"
+    node_js_inst=1
+  else
+    node_js_inst=0
+  fi
+else
+  echo >&2
+  echo -e "node\033[91;5;1m FAILED \033[0m"
+  node_js_inst = 0
+fi
+
+if [ x"$node_js_inst" = x"0" ]; then
+  echo "OpenFPM require node.js but it's not installed, searching a solution... "
+  solve_nodejs $platform
+
+  if haveProg node; then
+
+    dgc_major=$(node --version | grep v | sed 's/v\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)/\1/g')
+    dgc_middle=$(node --version | grep v | sed 's/v\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)/\2/g')
+    dgc_minor=$(node --version | grep v | sed 's/v\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)/\3/g')
+
+    if [ x"$dgc_major" = x"10" -a x"$dgc_middle" -gt x"14"  ]; then
+      echo -e "node\033[92;1m SUCCESS \033[0m"
+      node_js_inst=1
+    else
+      node_js_inst=0
+    fi
+  else
+    echo >&2
+    echo -e "node\033[91;5;1m FAILED \033[0m"
+    node_js_inst = 0
+  fi
+
+fi
 
 if haveProg gdbserver; then
   echo -e "gdbserver\033[92;1m SUCCESS \033[0m"
