Upgrade provide message

diff --git a/script/update_openfpm b/script/update_openfpm
--- a/script/update_openfpm
+++ b/script/update_openfpm
@@ -68,6 +68,12 @@ function update_openfpm()
     fi
   else
     ./install $dir_prev_inst $for_opt
+    if [ $? -ne 0 ]; then
+      echo -e "Upgrade summary\033[91;5;1m FAILED \033[0m"
+    else
+      echo -e "Upgrade summary\033[92;5;1m SUCCEED \033[0m"
+      echo -e "To make the upgrade active do: \033[1m make install \033[0m"
+    fi
   fi
 
 }
