Latest submodules and updated yml to include bundle build

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,7 @@ jobs:
     steps:
       - name: Install dependencies
         run: |
-          yum install -y openssh-clients cmake wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel
+          yum install -y openssh-clients cmake cpack wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel
           ln -s /usr/bin/python3 /usr/bin/python
       - uses: actions/checkout@v3
         with:
@@ -26,3 +26,65 @@ jobs:
           key: dependencies-${{ github.ref }}
       - name: Build
         run: ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
+
+      - name: Create and upload bundle
+        run: |
+          cd build
+          source $HOME/openfpm_vars
+          export DEP_PACKING=/usr/local/openfpm/dependencies/ ;
+          printf " -DCPACK_RUN_INSTALL_DEPENDENCIES=ON" >> cmake_build_options;
+          cp $HOME/openfpm_vars /usr/local/openfpm/dependencies/
+          bash cmake_build_options;
+          echo "Calling CPACK"
+          cpack -G $generator
+          
+          if [ $? -ne 0 ]; then
+            echo "Error creating package"
+            exit 1
+          fi
+
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: openfpm_almalinux
+          path: ./openfpm_pdata-$ofp_version-Almalinux.pkg
+
+  build_macos:
+    runs-on: macos-latest
+    steps:
+      - name: Install dependencies
+        run: |
+          brew install cmake cpack wget git gcc gfortran python3 bzip2 diffutils zlib
+          ln -s /usr/local/bin/python3 /usr/local/bin/python
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+      - name: Cache dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/openfpm_dependencies/
+          key: dependencies-${{ github.ref }}
+      - name: Build
+        run: ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
+
+      - name: Create and upload bundle
+        run: |
+          cd build
+          source $HOME/openfpm_vars
+          export DEP_PACKING=/usr/local/openfpm/dependencies/ ;
+          printf " -DCPACK_RUN_INSTALL_DEPENDENCIES=ON" >> cmake_build_options;
+          cp $HOME/openfpm_vars /usr/local/openfpm/dependencies/
+          bash cmake_build_options;
+          echo "Calling CPACK"
+          cpack -G $generator
+          
+          if [ $? -ne 0 ]; then
+            echo "Error creating package"
+            exit 1
+          fi
+
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: openfpm_macos
+          path: ./openfpm_pdata-$ofp_version-Darwin.pkg
